disabled_rules:
  - trailing_whitespace

included:
  - SimpleInvesting

excluded:
  - Pods

force_cast: warning
force_try:
  severity: warning
line_length: 120
file_length:
  warning: 600
  error: 800
type_name:
  min_length: 3
function_parameter_count: 5
identifier_name:
  min_length:
    error: 3
  excluded:
    - i
    - j
    - x
    - y
    - z
    - id
vertical_whitespace:
  max_empty_lines: 1
reporter: "xcode"
